# Generated by Django 4.1.3 on 2022-12-17 10:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0006_relatedinformation_publications"),
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillquiz",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resume.skill",
            ),
            preserve_default=False,
        ),
    ]
