# Generated by Django 4.1.3 on 2023-01-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_rename_ans1_skillquiz_a_rename_ans2_skillquiz_b_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillquizresult",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
