# Generated by Django 4.1.3 on 2023-02-04 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0004_skillquizresult_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skillquiz",
            name="a",
        ),
        migrations.RemoveField(
            model_name="skillquiz",
            name="b",
        ),
        migrations.RemoveField(
            model_name="skillquiz",
            name="c",
        ),
        migrations.RemoveField(
            model_name="skillquiz",
            name="correct_ans",
        ),
        migrations.RemoveField(
            model_name="skillquiz",
            name="d",
        ),
        migrations.RemoveField(
            model_name="skillquiz",
            name="skill",
        ),
        migrations.RemoveField(
            model_name="skillquiz",
            name="title",
        ),
        migrations.AddField(
            model_name="skillquiz",
            name="name",
            field=models.CharField(default="A", max_length=50),
        ),
        migrations.CreateModel(
            name="SkillQuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=550)),
                ("a", models.CharField(max_length=350)),
                ("b", models.CharField(max_length=350)),
                ("c", models.CharField(blank=True, max_length=350, null=True)),
                ("d", models.CharField(blank=True, max_length=350, null=True)),
                ("correct_ans", models.CharField(max_length=400)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.skillquiz"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
