# Generated by Django 4.1.3 on 2023-02-04 17:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0005_remove_skillquiz_a_remove_skillquiz_b_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SkillQuiz",
            new_name="Skills",
        ),
    ]
