# Generated by Django 4.1.3 on 2023-02-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_rename_skillquiz_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skills",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
