# Generated by Django 4.1.3 on 2022-12-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_remove_project_project_image_projectimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectimage",
            name="title",
        ),
        migrations.AddField(
            model_name="project",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
