# Generated by Django 4.1.3 on 2022-12-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_remove_projectimage_title_project_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="achievement",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="sponsors_due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
