# Generated by Django 4.1.3 on 2022-12-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_project_achievement_project_sponsors_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="achievement",
        ),
        migrations.AddField(
            model_name="project",
            name="sponsor_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
