# Generated by Django 4.1.3 on 2023-01-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_projectactivity_delete_projectachievement"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
