# Generated by Django 4.1.3 on 2022-12-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_skill_relatedinformation_achievement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="portfolio_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
