# Generated by Django 4.1.3 on 2022-12-10 21:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0004_alter_skill_portfolio_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionalinstitute",
            name="responsibility",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500),
                blank=True,
                null=True,
                size=50,
                verbose_name="residue payment remainder days",
            ),
        ),
    ]
