# Generated by Django 4.1.3 on 2022-12-17 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resume", "0006_relatedinformation_publications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="educationinstitute",
            name="name",
        ),
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=350)),
                (
                    "institute_type",
                    models.CharField(
                        choices=[
                            ("school", "School"),
                            ("college", "College"),
                            ("university", "University"),
                        ],
                        max_length=30,
                        verbose_name="Institute Type",
                    ),
                ),
                ("total_member", models.IntegerField(default=0)),
                ("total_project", models.IntegerField(default=0)),
                ("total_publication", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="educationinstitute",
            name="institute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education_institute",
                to="resume.institute",
            ),
            preserve_default=False,
        ),
    ]
