# Generated by Django 4.1.3 on 2022-12-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_professionalinstitute_responsibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='total_member',
            new_name='total_members',
        ),
        migrations.RenameField(
            model_name='institute',
            old_name='total_project',
            new_name='total_projects',
        ),
        migrations.RenameField(
            model_name='institute',
            old_name='total_publication',
            new_name='total_publications',
        ),
    ]
