# Generated by Django 4.1.3 on 2023-01-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0009_rename_total_member_institute_total_members_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institute",
            name="total_gpa",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="institute",
            name="total_graduates",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="institute",
            name="total_job_placement",
            field=models.IntegerField(default=0),
        ),
    ]
