# Generated by Django 4.1.3 on 2023-02-04 17:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_alter_skillquizresult_skill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resume", "0013_remove_skill_name_skill_skill"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skill",
            new_name="UserSkill",
        ),
    ]
